# 2D Numpy in Python

Nach dieser Uebung sollte ich in der Lage sein, fast alles mit Numpy zu machen.

### Create a 2D Numpy Array

In [3]:
# Let's start with importing the libraries

import numpy as np
import matplotlib.pyplot as plt

Create a list with 3 nested lists of each of equal size

In [2]:
# Create

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Convert the list to Numpy Array.<br>
Every element is the same type

In [4]:
A = np.array(a)
A

NameError: name 'a' is not defined

Use the attribute ndim

In [5]:
A.ndim

NameError: name 'A' is not defined

In [6]:
A.shape # retuns the dimension

(3, 3)

In [6]:
A.size # total number of elements

NameError: name 'A' is not defined

Access the element of the second row and third column

In [8]:
A[1,2]

23

In [9]:
# Access the element on the second row and third column

A[1][2]

23

In [10]:
# Access the element on the first row and first column

A[0][0]

11

In [11]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
# Access the element on the first row and first and second columns

A[0,0:2]

array([11, 12])

In [13]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

## Basic Operations

In [14]:
# Create a numpy array X

X = np.array([[1,0], [0,1]])
X

array([[1, 0],
       [0, 1]])

In [15]:
#Create a numpy array Y

Y = np.array([[2,1], [1,2]])
Y

array([[2, 1],
       [1, 2]])

In [17]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [20]:
Z = 2*Y
Z

array([[4, 2],
       [2, 4]])

We can also perform matrix multiplication witht the numpy arrays A and B as follows:

In [9]:
# Define matrix A

A = np.array([[0,1,1], [1,0,1]])
A



array([[0, 1, 1],
       [1, 0, 1]])

In [10]:
# Define matrix B

B = np.array([[1,1], [1,1], [-1,1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [11]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [12]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

Attribute T to calculate the transposed matrix

In [13]:
# Create a matrix C

C = np.array([[1,1], [2,2], [3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [14]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])